# Generated by Django 4.2.16 on 2024-10-09 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='experience',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='salary',
            new_name='happy_customers',
        ),
        migrations.RemoveField(
            model_name='about',
            name='type',
        ),
    ]
